COMMAND_HANDLER = "command-handler"
COMMAND_SANDER = "command-sender"
DIRECT_COMMAND_SANDER = "direct-command-sender"
SERVICE_SUBSCRIBER = "service-subscriber"
SERVICE_PROVIDER = "service-provider"
PROCEDURE_HANDLER = "procedure-handler"
PROCEDURE_CALLER = "procedure-caller"
CONTROL_SERVER = "control-server"
