<?xml version="1.0" encoding="UTF-8"?>
<process name="template" address="{IP}" port="{PORT}">
    <control-server address="{CONTROL_IP}" port="{CONTROL_PORT}"/>
    <register>
        <command>{COMMAND_NAME}</command>
        <service duration="{DURATION}" size="{SIZE}" repeat="{REPEAT}">{SERVICE_NAME}</service>
        <procedure duration="{DURATION}">{PROCEDURE_NAME}</procedure>
    </register>
    <request>
        <service>{SERVICE_NAME}</service>
    </request>
    <send repeat="{REPEAT}" duration="{DURATION}" size="{SIZE}">
        <procedure>{PROCEDURE_NAME}</procedure>
        <command>{COMMAND_NAME}</command>
        <direct-command address="{TARGETED_IP}" port="{TARGETED_PORT}">{COMMAND_NAME}</direct-command>
        <direct-command process="{TARGETED_PROCESS}">{COMMAND_NAME}</direct-command>
    </send>
</process>
